app/sesiones/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, ValidationError


class LoginForm(FlaskForm):
    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    recuerdame = BooleanField(label="Recuerdame")

class UsuarioForm(FlaskForm):

    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    passwordRepeat = PasswordField(label="Repita la contraseña", validators=[
        DataRequired(message="La repetición de la contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    nombre = StringField(label="Nombre", validators=[
        DataRequired(message="El nombre es obligatorio"),
        Length(max=20, message="El nombre no puede ser superior a 10 caracteres")
        ])

    apellidos = StringField(label="Apellidos", validators=[
        DataRequired(message="Los apellidos son obligatorio"),
        Length(max=50, message="Los apellidos no pueden superar los 50 caracteres")
        ])

    # submit = SubmitField(label="Dar de alta")

    def validate_password(form,field):
        if not password_check(form.password.data):
            raise ValidationError("La contraseña no cumple el formato. Debe tener al menos un dígito, mayúsculas, minúsculas y caráteres especiales.")
        if field.data != form.passwordRepeat.data:
            raise ValidationError("No coinciden las contraseñas")

    def validate_passwordRepeat(form, field):
        if field.data != form.password.data:
            raise ValidationError("No coinciden las contraseñas")

def password_check(passwd):

    SpecialSym = ['#', '$', '%', '&']
    val = True

    if not any(char.isdigit() for char in passwd):
        val = False

    if not any(char.isupper() for char in passwd):
        val = False

    if not any(char.islower() for char in passwd):
        val = False

    if not any(char in SpecialSym for char in passwd):
        val = False

    return val

app/sesiones/__init__.py
from flask import Blueprint
sesiones = Blueprint('sesiones', __name__, template_folder='templates', static_folder='static')

from . import routes

app/sesiones/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import login_user, logout_user, current_user

import app
from . import sesiones
from .forms import LoginForm
from .forms import UsuarioForm
from ..login.models import Usuario

PEEPER = "ClaveSecretaPeeper"

@app.login_manager.user_loader
def load_user(user_id):
    return Usuario.get_by_id(user_id)

@sesiones.route('/')
def index():
    return render_template('index.html')

@sesiones.route("/logoutsession/")
def logoutsession():
    logout_user()
    return redirect(url_for('sesiones.index'))

@sesiones.route("/welcome/")
def welcome():
    return render_template("welcome.html")

@sesiones.route("/altaUsuarioSesiones/", methods=["GET","POST"])
def altaUsuarioSesiones():
    if current_user.is_authenticated:
        return redirect(url_for("sesiones.welcome"))
    error = ""
    form = UsuarioForm(request.form)
    if app.recaptcha.verify():
        if form.validate_on_submit():
            if app.recaptcha.verify():
                try:
                    usuario = Usuario()
                    usuario.username = form.username.data
                    password = PEEPER + form.password.data
                    usuario.set_password(password)
                    usuario.nombre = form.nombre.data
                    usuario.apellidos = form.apellidos.data
                    usuario.create()
                    return redirect(url_for('sesiones.loginSesiones'))
                except Exception as e:
                    error = "No se ha podido dar de alta " + e.__str__()
                    app.logger.error(error)
            else:
                error = "Captcha incorrecto. Eres un robot."
    return render_template("altaUsuarioSesiones.html", form=form, error=error)

@sesiones.route("/loginSesiones/", methods=["GET","POST"])
def loginSesiones():
    if current_user.is_authenticated:
        return redirect(url_for("private.indexcliente"))
    error = ""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        password = PEEPER + form.password.data
        usuario = Usuario.get_by_username(username)
        if app.recaptcha.verify():
            if usuario and usuario.check_password(password):
                login_user(usuario, form.recuerdame.data)
                return redirect(url_for("private.indexcliente"))
            else:
                error = "Usuario y/o contraseña incorrecta"
                app.logger.warning("Se ha intentado iniciar sesión con el usuario: "+username)
        else:
            error = "Captcha incorrecto. Eres un robot."
    return render_template("loginSesiones.html", form=form, error=error)

app/sesiones/templates/altaUsuarioSesiones.html
{% from 'base/_helpers.html' import generarForm with context %}
{% extends "base/base.html" %}
{% block titulo %}Hash Peeper{% endblock %}
{% block contenido %}
<h1>Alta Usuario sesiones</h1>
    {% if error %}
        <div class="row">
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4">
            <form action="{{ url_for('sesiones.altaUsuarioSesiones') }}" method="post">
                {{ form.csrf_token() }}
                {{ generarForm(form) }}
                {{ recaptcha }}
                <br>
                <input type="submit" value="Dar de alta" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

app/sesiones/templates/index.html
{% extends "base/base.html" %}
{% block titulo %}Inicio{% endblock %}
{% block contenido %}
<div class="text-center">
    <h1 class="display-4">Tema 3</h1>
    <p>Formas de gestionar las sesiones y cookies</p>
</div>
{% endblock %}

app/sesiones/templates/loginSesiones.html
{% from 'base/_helpers.html' import generarForm with context %}
{% extends "base/base.html" %}
{% block titulo %}Login Usuario Sesiones{% endblock %}
{% block contenido %}
<h1>Login Sesiones</h1>
    {% if error %}
        <div class="row">
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4">
            <form action="{{ url_for('sesiones.loginSesiones') }}" method="post">
                {{ form.csrf_token() }}
                {{ generarForm(form) }}
                {{ recaptcha }}
                <br>
                <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
                <br>
            </form>
        </div>
    </div>
{% endblock %}

app/sesiones/templates/mostrarSesion.html
{% extends "base/base.html" %}
{% block titulo %}Crear Cookie{% endblock %}
{% block contenido %}
<div class="text-center">
    <h1 class="display-4">Mostrar Sesiones</h1>
    Nombre:{{ nombre }}
    <br/>
    Apellidos:{{ apellidos }}
        <form action="{{ url_for('sesiones.mostrarsesion') }}" method="post">
        <input type="submit" value="Borrar" class="bg-danger">
    </form>
</div>
{% endblock %}

app/sesiones/templates/welcome.html
{% extends "base/base.html" %}
{% block titulo %}Inicio{% endblock %}
{% block contenido %}
<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Bienvenido</p>
</div>
{% endblock %}