app/login/models.py
from flask_login import UserMixin
from sqlalchemy.exc import IntegrityError
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

import app

class Usuario(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(15), unique=True, nullable=False)
    password = db.Column(db.String(), nullable=False)
    nombre = db.Column(db.String(20), nullable=False)
    apellidos = db.Column(db.String(50), nullable=False)
    is_admin = db.Column(db.Boolean, default=False)

    def create(self):
        try:
            db.session.add(self)
            db.session.commit()
            app.logger.info("Usuario con el username: " + self.username + " insertado correctamente.")
        except IntegrityError:
            app.logger.error("Error: ya existe un cliente con el mismo DNI.")
            raise Exception("Error: ya existe un usuario con el mismo username")

    def __str__(self):
        return self.apellidos + ', ' + self.nombre

    @staticmethod
    def get_by_id(id):
        return Usuario.query.get(id)

    @staticmethod
    def get_by_username(username):
        return Usuario.query.filter_by(username=username).first()

    def set_password(self, password):
        method = "pbkdf2:sha256:260000"
        self.password = generate_password_hash(password, method=method)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, PasswordField
from wtforms.validators import DataRequired, Length, ValidationError


class LoginForm(FlaskForm):
    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])


class UsuarioForm(FlaskForm):

    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    passwordRepeat = PasswordField(label="Repita la contraseña", validators=[
        DataRequired(message="La repetición de la contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    nombre = StringField(label="Nombre", validators=[
        DataRequired(message="El nombre es obligatorio"),
        Length(max=20, message="El nombre no puede ser superior a 10 caracteres")
        ])

    apellidos = StringField(label="Apellidos", validators=[
        DataRequired(message="Los apellidos son obligatorio"),
        Length(max=50, message="Los apellidos no pueden superar los 50 caracteres")
        ])

    # submit = SubmitField(label="Dar de alta")

    def validate_password(form,field):
        if not password_check(form.password.data):
            raise ValidationError("La contraseña no cumple el formato. Debe tener al menos un dígito, mayúsculas, minúsculas y caráteres especiales.")
        if field.data != form.passwordRepeat.data:
            raise ValidationError("No coinciden las contraseñas")

    def validate_passwordRepeat(form, field):
        if field.data != form.password.data:
            raise ValidationError("No coinciden las contraseñas")

def password_check(passwd):

    SpecialSym = ['#', '$', '%', '&']
    val = True

    if not any(char.isdigit() for char in passwd):
        val = False

    if not any(char.isupper() for char in passwd):
        val = False

    if not any(char.islower() for char in passwd):
        val = False

    if not any(char in SpecialSym for char in passwd):
        val = False

    return val

app/login/__init__.py
from flask import Blueprint
login = Blueprint('login', __name__, template_folder='templates', static_folder='static')

from . import routes

app/login/routes.py
from flask import render_template, request, redirect, url_for
from flask_login import login_user, logout_user, current_user

import app
from . import login
from .forms import LoginForm
from .forms import UsuarioForm
from .models import Usuario

PEEPER = "ClaveSecretaPeeper"

@app.login_manager.user_loader
def load_user(user_id):
    return Usuario.get_by_id(user_id)

@login.route('/')
def index():  # put application's code here
    return render_template('index.html')

@login.route("/welcome/")
def welcome():
    return render_template("welcome.html")

@login.route("/altaUsuario/", methods=["GET","POST"])
def altaUsuario():
    if current_user.is_authenticated:
        return redirect(url_for("login.welcome"))
    error = ""
    form = UsuarioForm(request.form)
    if form.validate_on_submit():
        try:
            usuario = Usuario()
            usuario.username = form.username.data
            password = PEEPER + form.password.data
            usuario.set_password(password)
            usuario.nombre = form.nombre.data
            usuario.apellidos = form.apellidos.data
            usuario.create()
            app.logger.info("Se ha dado de alta el usuario: "+usuario.username)
            return redirect(url_for('login.welcome'))
        except Exception as e:
            error = "No se ha podido dar de alta " + e.__str__()
            app.logger.error(error)
    return render_template("altaUsuarioSesiones.html", form=form, error=error)

@login.route("/loginHashPeeper/", methods=["GET","POST"])
def loginHashPeeper():
    if current_user.is_authenticated:
        return redirect(url_for("login.indexcliente"))
    error = ""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        password = PEEPER + form.password.data
        usuario = Usuario.get_by_username(username)
        if app.recaptcha.verify():
            if usuario and usuario.check_password(password):
                app.logger.info("Ha accedido el usuario: " + usuario.username)
                return redirect(url_for("login.indexcliente"))
            else:
                error = "Usuario y/o contraseña incorrecta"
                app.logger.error(error)
        else:
            error = "Captcha incorrecto. Eres un robot."
    return render_template("loginSesiones.html", form=form, error=error)

app/login/templates/altaUsuario.html
{% from 'base/_helpers.html' import generarForm with context %}
{% extends "base/base.html" %}
{% block titulo %}Hash Peeper{% endblock %}
{% block contenido %}
<h1>Almacenamiento de la contraseña Hash con Pimienta</h1>
    {% if error %}
        <div class="row">
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4">
            <form action="{{ url_for('login.altaUsuario') }}" method="post">
                {{ form.csrf_token() }}
                {{ generarForm(form) }}
                <input type="submit" value="Dar de alta" class="btn btn-primary"/>
            </form>
        </div>
    </div>
{% endblock %}

app/login/templates/index.html
{% extends "base/base.html" %}
{% block titulo %}Inicio{% endblock %}
{% block contenido %}
<div class="text-center">
    <h1 class="display-4">Tema 3</h1>
    <p>Formas de gestionar la contraseña</p>
</div>
{% endblock %}

app/login/templates/loginHashPeeper.html
{% from 'base/_helpers.html' import generarForm with context %}
{% extends "base/base.html" %}
{% block titulo %}Login Hash Peeper{% endblock %}
{% block contenido %}
<h1>Login Hash con Pimienta</h1>
    {% if error %}
        <div class="row">
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-4">
            <form action="{{ url_for('login.loginHashPeeper') }}" method="post">
                {{ form.csrf_token() }}
                {{ generarForm(form) }}
                {{ recaptcha }}
                <input type="submit" value="Iniciar Sesión" class="btn btn-primary"/>
                <br>
            </form>
        </div>
    </div>
{% endblock %}