app/private/models.py
from sqlalchemy.exc import IntegrityError
from app import db

import app

class Cliente(db.Model):
    dni = db.Column(db.String(10),primary_key=True)
    nombre = db.Column(db.String(20),nullable=False)
    apellidos = db.Column(db.String(50))
    imagen = db.Column(db.String())

    def save(self):
        try:
            db.session.add(self)
            db.session.commit()
            app.logger.info("Cliente con el DNI: "+self.dni+" insertado correctamente.")
        except IntegrityError:
            app.logger.error("Error: ya existe un cliente con el mismo DNI.")
            raise Exception("Error: ya existe un cliente con el mismo DNI")

app/private/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from flask_wtf.file import FileRequired, FileAllowed, FileField
from wtforms.validators import DataRequired, Length, ValidationError
from PIL import Image
import os

class ClienteForm(FlaskForm):


    dni = StringField(label="DNI", validators=[
        DataRequired(message="El campo DNI es obligatorio"),
        Length(max=10, message="El campo DNI no tiene un formato válido.")
    ])

    nombre = StringField(label="Nombre", validators=[
        DataRequired(message="El campo nombre es obligatorio"),
        Length( max=20, message="El campo nombre debe ser entre 5 y 20 caracteres")
    ])

    apellidos = StringField(label="Apellidos", validators=[
        DataRequired(message="El campo apellidos es obligatorio"),
        Length(min=5, max=50, message="El campo apellidos debe ser entre 5 y 20 caracteres")
    ])

    imagen = FileField(label="Imagen", validators=[
        FileRequired(message="El campo imagen es obligatorio"),
        FileAllowed(['jpg','png'], message="Solo jpg y png")
    ])

    submit = SubmitField(label="Enviar")


    # Lo puse porque quería probar otra validación más y ya pues lo dejo
    def validate_dni(form,field):
        tabla = "TRWAGMYFPDXBNJZSQVHLCKE"
        dig_ext = "XYZ"
        reemp_dig_ext = {'X': '0', 'Y': '1', 'Z': '2'}
        numeros = "1234567890"
        dni = form.dni.data
        if len(dni) == 9:
            dig_control = dni[8]
            dni = dni[:8]
            if dni[0] in dig_ext:
                dni = dni.replace(dni[0], reemp_dig_ext[dni[0]])
            if len(dni) != len([n for n in dni if n in numeros]) \
                   and tabla[int(dni) % 23] == dig_control:
                raise ValidationError("El DNI introducido no tiene formato válido " )
        else:
            raise ValidationError("El DNI introducido no es válido abajo")

app/private/__init__.py
from flask import Blueprint
private = Blueprint('private', __name__, template_folder='templates', static_folder='static')

from . import routes

app/private/routes.py
import base64

from flask import render_template, request, redirect, url_for
from flask_login import login_required, logout_user, current_user
from werkzeug.datastructures import CombinedMultiDict

from . import private
from .forms import ClienteForm
from .models import Cliente

import app

@private.route("/indexcliente/", methods=["GET","POST"])
@login_required
def indexcliente():
    clientes = Cliente.query.all()

    return render_template("indexcliente.html", clientes = clientes)

@private.route("/altaCliente/", methods=["GET","POST"])
@login_required
def altaCliente():
    form = ClienteForm(CombinedMultiDict((request.files, request.form)))
    if form.validate_on_submit():
        dni = request.form.get("dni")
        nombre = request.form.get("nombre")
        apellidos = request.form.get("apellidos")

        encoded_bytes = base64.b64encode(form.imagen.data.read())

        if  len(encoded_bytes) > 1024*1024:
            form.imagen.errors.append("Tamaño máximo 1MB")
            return render_template("altaUsuarioSesiones.html", form =  form)
        else:
            encoded_string = str(encoded_bytes).replace("b'", "").replace("'", "")
            cliente = Cliente()
            cliente.dni = dni
            cliente.nombre = nombre
            cliente.apellidos = apellidos
            cliente.imagen = encoded_string
            cliente.save()
            clientes = Cliente.query.all()
            app.logger.info("Se ha dado de alta el cliente con DNI: "+cliente.dni)
        return render_template("indexcliente.html", clientes=clientes)

    return render_template("altaUsuarioSesiones.html", form = form)

app/private/templates/altaCliente.html
{% extends "base/base.html" %}
{% block titulo %}Clientes{% endblock %}
{% block contenido %}
<h1>Alta Cliente</h1>
<div class="row">

    <form action="{{ url_for('private.altaCliente') }}" method="post" enctype="multipart/form-data">
        {{ form.csrf_token() }}
        <div class="mb-3 mt-3">
             {{ form.dni.label(class="form-label") }}
             {{ form.dni(class="form-control") }}
             {% for error in form.dni.errors %}
                <span class="bg-danger">{{ error }}</span>
             {% endfor %}
        </div>
        <div class="mb-3 mt-3">
            {{ form.nombre.label(class="form-label") }}
            {{ form.nombre(class="form-control") }}
        </div>
        <div class="mb-3 mt-3">
            {{ form.apellidos.label(class="form-label") }}
            {{ form.apellidos(class="form-control") }}
            {% for error in form.apellidos.errors %}
                <span class="bg-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="mb-3 mt-3">
            {{ form.imagen.label(class="form-label") }}
            {{ form.imagen(class="form-control") }}
            {% for error in form.imagen.errors %}
                <span class="bg-danger">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="mb-3 mt-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>

    </form>

</div>
{% endblock %}

app/private/templates/indexcliente.html
{% extends "base/base.html" %}
{% block titulo %}Clientes{% endblock %}
{% block contenido %}
<h1>Clientes</h1>
<div class="row">

<table class="table">
  <thead>
    <tr>
      <th scope="col">DNI</th>
      <th scope="col">Nombre</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Imagen</th>
    </tr>
  </thead>
  <tbody>
    {% for cliente in clientes %}
        <tr>
          <th scope="row">{{ cliente.dni }}</th>
          <td>{{ cliente.nombre }}</td>
          <td>{{ cliente.apellidos }}</td>
          <td><img src="data:image/jpg;base64,{{ cliente.imagen }}" alt="img_data" id="imgslot"/></td>
        </tr>
    {% endfor %}
  </tbody>
</table>


</div>
{% endblock %}